[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dalia"
authors = [
    { name = "Lisa Gaedke-Merzhaeuser", email = "lisa.gaedke.merzhaeuser@usi.ch" },
    { name = "Vincent Maillou", email = "vmaillou@iis.ee.ethz.ch" },
    { name = "Alexandros Nikolaos Ziogas", email = "alziogas@iis.ee.ethz.ch" },
]
description = "Python implementation of the method of integrated nested Laplace approximations (INLA)"
readme = "README.md"
license = {file="LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
keywords = ["INLA", "Bayesian", "statistics"]
dynamic = ["version"]
requires-python = ">=3.11"

dependencies = [
    "numpy>=1.23.2",
    "scipy>=1.15.0",
    "matplotlib>=3.10.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
# High-performance computing features
mpi4py = ["mpi4py"]
cupy = ["cupy==13.2.0"]
serinv = ["serinv @ git+https://github.com/vincent-maillou/serinv"]

# Development tools (for contributors)
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mpi",
    "pytest-xdist",
    "coverage",
    "black",
    "isort",
    "ruff",
    "just",
    "pre-commit",
]

all = [
    "dalia[dev]"
]

[project.urls]
Homepage = "https://github.com/dalia-project/DALIA"
Repository = "https://github.com/dalia-project/DALIA"
Issues = "https://github.com/dalia-project/DALIA/issues"
Documentation = "https://dalia.readthedocs.io"
Changelog = "https://github.com/dalia-project/DALIA/blob/main/CHANGELOG.md"

[tool.setuptools.packages.find]
where = ["src"]
include = ["dalia*"]
namespaces = false

[tool.setuptools.dynamic]
version = { attr = "dalia.__about__.__version__" }

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]
known_first_party = ["dalia"]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]